name: findmycar
description: A smart parking assistant app
publish_to: 'none'
version: 2.3.3+11


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  cloud_functions: ^5.0.0
  firebase_messaging: ^15.0.0
  
  # Google Sign In
  google_sign_in: ^6.2.0
  
  # Sign in with Apple
  sign_in_with_apple: ^6.1.0
  
  # Location & Maps
  geolocator: ^13.0.0
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  
  # Bluetooth
  flutter_blue_plus: ^1.32.9
  
  # UI & State Management
  provider: ^6.1.0
  go_router: ^14.0.0
  
  # Storage & Media
  image_picker: ^1.1.0
  permission_handler: ^11.3.0
  video_player: ^2.9.0
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.0
  http: ^1.2.0
  google_fonts: ^6.1.0
  confetti: ^0.7.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.2
  package_info_plus: ^8.0.0
  purchases_flutter: ^9.10.5
  purchases_ui_flutter: ^9.10.5
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/intro1.mp4
    - assets/images/intro2.mp4
    - assets/icon/app_icon.png
    - assets/icon/app_icon_splash.png
    - assets/icon/carIcon.png
    - assets/icon/carIcon_red.png
    - assets/icon/carIcon_black.png
    - assets/icon/light.jpg
    - assets/icon/dark.jpg 

